### ISSUE TITLE
Userstory 1

### ISSUE THREAD

**Issue by AntjeWitte** [AntjeWitte/capstone-project#1]
## Value Proposition

**As an** employee in Quality Assurance
**I want to** have a form with input fields
**so that** pralines can be added and deleted in the database.  
​

## Description

![Praline_2](https://github.com/AntjeWitte/capstone-project/assets/127970636/06b5b53c-4286-400d-86b1-412826c29f02)

​

## Acceptance Criteria

- [x] Pralines must be created and deleted in the database MongoDB
- [x] There must be a form field to enter data for new pralines
- [x] There must be two buttons one for creating and one for deleting pralines

## Tasks

- [x] Add two buttons in the top, one with "Praline bearbeiten" and one with "Praline löschen"
- [x] Add a userform with input fields to enter all information for a new praline
- [x] Add a (+) button next to "Zutaten" and "Allergenspuren"
- [x] When clicking the (+) button the entered ingredient or trace should appear below the input field
- [x] Next to the new added ingredient or trace there should be a (-) button
- [x] When clicking the (-) button the displayed ingredient or trace should be deleted
- [x] There should be a button or other option to upload a picture
- [x] Add two buttons at the buttom, one with "abbrechen" and one with "speichern / hinzufügen"
- [x] When clicking the "speichern / hinzufügen" button, the entered data from the form should be saved in the database
- [x] When clicking the "Praline löschen" button, the data in the form should be erased and the praline should be deleted from the database
- [x] There should be an error when an input field is left empty accept for the allergy traces, they are optional 
      ​

## Complexity

L

**Comment by florianblaschke** [comment]
Will I be able to see how many/which Pralines I have created?

**Comment by AntjeWitte** [comment]
No, not at this point. The display page will be a pop up page, this will be my next userstory.
