### ISSUE TITLE
Userstory 2

### ISSUE THREAD

**Issue by AntjeWitte** [AntjeWitte/capstone-project#3]
## Value Proposition

**As an** employee in Quality Assurance
**I want to** have a pop up page with the pralines listed
**so that** I can see and edit the pralines 
​

## Description

![Praline_2](https://github.com/AntjeWitte/capstone-project/assets/127970636/e0639455-a999-4954-9572-28d25ab90acd)

![Praline_3](https://github.com/AntjeWitte/capstone-project/assets/127970636/8d96197a-83bd-4e02-8318-be1757be888d)

​

## Acceptance Criteria

- [x] When clicking the "Praline bearbeiten" button on the "Pralinen anpassen" page there should be a pop up page
- [x] On the pop up page all pralines from the database are listed
- [x] When selecting one praline you should go back to the "Pralinen anpassen" page and be able to change the praline data and save the changes
      ​

## Tasks

- [x] Create pop up page
- [x] Link the "Praline bearbeiten" button to the pop up page
- [x] All pralines from the database are displayed on the pop up page
- [x] There is an "Abbrechen/keine" button on the pop up page, that links back to the "Pralinen anpassen" page
- [x] On the "Pralinen anpassen" page when changing data the changes are saved in the database
- [x] After saving the changes the form should be erased
      ​

## Complexity

M

**Comment by MiejkeHoltermann** [comment]
Ziemlich coole App Idee!
1. Hast du schon eine Datenbank angebunden oder arbeitest du erstmal mit einem Array, aus dem du die Daten ausliest? Dann würde ich das sonst noch anpassen.
2. Ich würde den Button vielleicht "Praline auswählen" oder so nennen? Weil der User ja auf den Button klickt und dann die Möglichkeit hat eine Praline auszuwählen die er bearbeiten will.

**Comment by AntjeWitte** [comment]
Genau, die App ist bereits an die Datenbank MongoDB angebunden. Pralinen hinzufügen und löschen klappt auch bereits. 

Der User soll auf der Seite "Pralinen anpassen" folgende Aktionen machen können: Praline neu hinzufügen, Praline löschen, Praline bearbeiten. 

Das Ansehen und Auswählen der Pralinen um sie zu einer virtuellen Pralinenschachtel zusammenzustellen ist der Fokus meiner Hauptseite, die noch nicht geschrieben ist. Das wird Userstory 3. 

"Bearbeiten" ist also in meinen Augen hier das richtige Wort.
