### ISSUE TITLE
Userstory 3

### ISSUE THREAD

**Issue by AntjeWitte** [AntjeWitte/capstone-project#6]
## Value Proposition

**As an** employee in Marketing or Development
**I want to** fill an empty praline box with pralines from the database
**so that** I can create a new praline selection and have the correct ingredient declaration automatically displayed
​

## Description

![Praline_1](https://github.com/AntjeWitte/capstone-project/assets/127970636/cc72bbc0-27e6-424e-b046-550644d84bfa)

​

## Acceptance Criteria

- [x] When clicking an empty spot in the praline box the praline list should appear
- [x] When selecting a praline from the list it should appear in the selected spot
- [x] The weight and ingredients below the praline box are added together with every new praline in the box
      ​

## Tasks

- [x] Create a new page with the heading "Neue Pralinenkreation"
- [x] Create a dropdown menu with number of pralines in the box
- [x] Create an input field for the name of the praline box
- [x] Create an empty praline box
- [x] When clicking an empty spot in the box, the pop up page with praline list should appear
- [x] When selecting one praline from the list the pop up page should be closed and the selected praline should appear in the right spot
- [x] Create a "zurücksetzen" button that clears the box
- [x] Write a function, that adds together the praline weights, ingredients and allergy traces with every new selected praline and displays them below the box
- [x] Create a print/save button that allows the user to print the page or save it as pdf
- [x] Create a "Pralinen bearbeiten" button that links to the page "Pralinen bearbeiten"
      ​

## Complexity

L

**Comment by florianblaschke** [comment]
Good US!

**Comment by JudithRe** [comment]
lgtm
