### ISSUE TITLE
Userstory 4

### ISSUE THREAD

**Issue by AntjeWitte** [AntjeWitte/capstone-project#8]
## Value Proposition

**As an** employee from a chocolate manufacturer 
**I want to** find a styled and easy to handle page 
**so that** I will have a nice user experience 
​

## Description

![Pralinen-App](https://github.com/AntjeWitte/capstone-project/assets/127970636/7a51f763-c6f9-43a9-9687-b7cf80035769)

## Acceptance Criteria

- [x] All visible components are styled
- [x] There are warning, error and success messages
      ​

## Tasks

- [x] Styled backgrounds
- [x] Styled buttons
- [x] Styled input fields
- [x] Styled fonts
- [x] Position, alignments and borders
- [x] Styled praline box
- [x] Styled praline list
- [x] Save a default picture if no picture is added to a new praline
- [x] Success message: new praline created 
- [x] Warnung message: delete praline
- [x] Warning message when clicking "Praline anpassen" on the praline box page: praline box will be reseted if leaving the page
- [x] Write at least three tests from the react-testing library
      ​

## Complexity

XL

**Comment by ninaassmann** [comment]
I guess the tests are not for the user, so would make more sense in the task area
